unit DBUShared.uConsts;

interface

const
  DEFAULT_USER_LIST_SEPARATOR = '^^^^^';

  CONFIGURATION_DEFAULT_USER_BLOCKED = True;
  CONFIGURATION_DEFAULT_USER_ADMINISTRATOR = False;

  ERROR_UNKNOWN: Byte = 0;
  ERROR_CONFIGURATION_OBJECT_NOT_EXISTS: Byte = 1;
  ERROR_USERS_OBJECT_NOT_EXISTS: Byte = 2;
  ERROR_USER_ALREADY_EXISTS: Byte = 3;
  ERROR_CAN_NOT_CREATE_USER_OBJECT: Byte = 4;
  ERROR_CAN_NOT_ADD_USER_OBJECT_TO_USERS: Byte = 5;
  SUCCESS_ADD_USER: Byte = 6;
implementation

end.
