unit OA5.uDefaultConsts;

interface

uses
  CastersPackage.uMysql,
  CastersPackage.uTLogMessagesType,
  CastersPackage.uTReportFolder;

const
  // вкладка "настройки интерфейса"
  DEFAULT_CONFIGURATION_ENABLE_SPLASH_AT_START = True;
  DEFAULT_CONFIGURATION_ENABLE_TOOLBAR = True;
  DEFAULT_CONFIGURATION_ENABLE_STATUSBAR = True;
  DEFAULT_CONFIGURATION_ENABLE_EDITBOX_HINTS = True;
  DEFAULT_CONFIGURATION_ENABLE_COMMON_SEARCH_EDITBOX = True;
  DEFAULT_CONFIGURATION_ENABLE_ID = False;
  DEFAULT_CONFIGURATION_ENABLE_MULTIBUFFER = True;
  DEFAULT_CONFIGURATION_ENABLE_QUIT_CONFIRMATION = True;

  // вкладка "настройки ведения протокола работы"
  DEFAULT_CONFIGURATION_ENABLE_LOG = True;
  DEFAULT_CONFIGURATION_KEEP_LOG_TYPES = [lmtError, lmtWarning, lmtInfo];
  DEFAULT_CONFIGURATION_ENABLE_FLUSH_LOG_ON_EXIT = True;
  DEFAULT_CONFIGURATION_ENABLE_FLUSH_LOG_ON_STRINGS_QUANTITY = True;
  DEFAULT_CONFIGURATION_FLUSH_LOG_ON_STRINGS_QUANTITY_VALUE = 10000;
  DEFAULT_CONFIGURATION_ENABLE_FLUSH_LOG_ON_CLEARING_LOG = True;
  DEFAULT_CONFIGURATION_ENABLE_FLUSH_LOG_ON_APPLY = False;
  DEFAULT_CONFIGURATION_ENABLE_CUSTOM_LOG_CLIENT = False;
  DEFAULT_CONFIGURATION_CUSTOM_LOG_CLIENT_VALUE = '';

  // вкладка "настройки положения диалоговых окон"
  DEFAULT_CONFIGURATION_ENABLE_DIALOG_CENTERED = True;
  DEFAULT_CONFIGURATION_DIALOG_LEFT = 0;
  DEFAULT_CONFIGURATION_DIALOG_TOP = 0;

  // вкладка "настройки процедуры логирования"
  DEFAULT_CONFIGURATION_ENABLE_STORE_LOGIN = False;
  DEFAULT_CONFIGURATION_ENABLE_STORE_PASSWORD = False;
  DEFAULT_CONFIGURATION_STORED_LOGIN = '';
  DEFAULT_CONFIGURATION_STORED_PASSWORD = '';
  DEFAULT_CONFIGURATION_ENABLE_AUTO_LOGON = False;

  // вкладка "подключения к серверу базы данных услуги"
  DEFAULT_CONFIGURATION_DBSERVER_HOST = 'RNE4SERVER';
  DEFAULT_CONFIGURATION_DBSERVER_PORT = MYSQL_PORT;
  DEFAULT_CONFIGURATION_DBSERVER_TIMEOUT = 30;
  DEFAULT_CONFIGURATION_DBSERVER_COMPRESSION = True;
  DEFAULT_CONFIGURATION_DBSERVER_LOGIN = 'root';
  DEFAULT_CONFIGURATION_DBSERVER_PASSWORD = 'sqladmin';
  DEFAULT_CONFIGURATION_DBSERVER_DATABESE = 'rne4';

  // вкладка "подключения к серверу системы обмена сообщениями"
  DEFAULT_CONFIGURATION_MESSAGESERVER_HOST = 'RNE4MESSAGESSERVER';
  DEFAULT_CONFIGURATION_MESSAGESERVER_PORT = MYSQL_PORT;
  DEFAULT_CONFIGURATION_MESSAGESERVER_TIMEOUT = 30;
  DEFAULT_CONFIGURATION_MESSAGESERVER_COMPRESSION = True;
  DEFAULT_CONFIGURATION_MESSAGESERVER_LOGIN = 'root';
  DEFAULT_CONFIGURATION_MESSAGESERVER_PASSWORD = 'sqladmin';
  DEFAULT_CONFIGURATION_MESSAGESERVER_DATABASE = 'rne4messages';

  // вкладка "настройки формирования отчётов"
  DEFAULT_CONFIGURATION_REPORT_FOLDER_TYPE = rfApplicationFolder;
  DEFAULT_CONFIGURATION_CUSTOM_REPORT_FOLDER_VALUE = '';
  DEFAULT_CONFIGURATION_ENABLE_OVERWRITE_CONFIRMATION = True;
  DEFAULT_CONFIGURATION_ENABLE_ASK_FOR_FILE_NAME = True;

  // вкладка "настройки прочие"
  DEFAULT_CONFIGURATION_ENABLE_LAUNCH_AT_STARTUP = False;
  DEFAULT_CONFIGURATION_ENABLE_PLAY_SOUND_ON_COMPLETE = True;
  DEFAULT_CONFIGURATION_ENABLE_AUTO_GET_MESSAGES = True;
  DEFAULT_CONFIGURATION_AUTO_GET_MESSAGES_CYCLE_DURATION_VALUE = 5;
  DEFAULT_CONFIGURATION_ENABLE_CUSTOM_HELP_FILE = False;
  DEFAULT_CONFIGURATION_CUSTOM_HELP_FILE_VALUE = '';

  // вкладка "настройки главного окна"
  DEFAULT_CONFIGURATION_MAIN_FORM_LEFT = 0;
  DEFAULT_CONFIGURATION_MAIN_FORM_TOP = 0;
  DEFAULT_CONFIGURATION_MAIN_FORM_WIDTH = 800;
  DEFAULT_CONFIGURATION_MAIN_FORM_HEIGHT = 600;
  DEFAULT_CONFIGURATION_MAIN_FORM_ENABLE_CENTERED = True;
  DEFAULT_CONFIGURATION_MAIN_FORM_ENABLE_FULL_SCREEN_AT_LAUNCH = False;

  // вкладка "настройки отображения информации"
  DEFAULT_CONFIGURATION_ORGANIZATION_PANEL_HEIGHT_VALUE = 100;
  DEFAULT_CONFIGURATION_ORGANIZATION_PANEL_ENABLE_HALF_HEIGHT = True;
  DEFAULT_CONFIGURATION_DATA_PANEL_WIDTH_VALUE = 340;
  DEFAULT_CONFIGURATION_DATA_PANEL_ENABLE_HALF_WIDTH = False;
  DEFAULT_CONFIGURATION_ENABLE_DATA_IN_OTHER_INFO_PANEL = True;
  DEFAULT_CONFIGURATION_ENABLE_MEASURE_LIST_AS_RICH_EDIT = True;
  DEFAULT_CONFIGURATION_ENABLE_MARK_SEARCHED_STRINGS = True;
  DEFAULT_CONFIGURATION_ENABLE_PUT_TOWN_AT_THE_END = False;

  DEFAULT_CONFIGURATION_CURRENT_PAGE = 0;
  DEFAULT_CONFIGURATION_ORGANIZATIONS_SORTED_BY_COLUMN = 0;
  DEFAULT_CONFIGURATION_MEASURES_SORTED_BY_COLUMN = 0;

  DEFAULT_MEASURE_AUTO_NORMALIZE_DATA = True;
  DEFAULT_MEASURE_ORGANIZATION_ID = -1;
  DEFAULT_MEASURE_TYPE: string = '';
  DEFAULT_MEASURE_NAME: string = '';
  DEFAULT_MEASURE_AUTHOR: string = '';
  DEFAULT_MEASURE_PRODUCER: string = '';
  DEFAULT_MEASURE_PERFORMER: string = '';
  DEFAULT_MEASURE_ORGANIZER: string = '';
  DEFAULT_MEASURE_TICKET_PRICE: string = '';
  DEFAULT_MEASURE_OTHER_INFO_RTF: AnsiString = '';
  DEFAULT_MEASURE_OTHER_INFO_PLANE: AnsiString = '';
  DEFAULT_MEASURE_HAS_UNKNOWN_DURATION = True;
  DEFAULT_MEASURE_HAS_START_DATETIME = False;
  DEFAULT_MEASURE_HAS_STOP_DATETIME = False;
  DEFAULT_MEASURE_START_DATETIME = 0;
  DEFAULT_MEASURE_STOP_DATETIME = 0;
  DEFAULT_MEASURE_DURATION_DAYS = 0;
  DEFAULT_MEASURE_DURATION_HOURS = 0;
  DEFAULT_MEASURE_DURATION_MINUTES = 0;
  DEFAULT_MEASURE_IS_PREMIER = False;
  DEFAULT_MEASURE_IS_TOUR = False;
  DEFAULT_MEASURE_IS_SPORT = False;
  DEFAULT_MEASURE_FOR_CHILDREN = False;
  DEFAULT_MEASURE_FOR_TEENAGERS = False;
  DEFAULT_MEASURE_FOR_ADULTS_ONLY = False;

  DEFAULT_PRIVILEGIES_ACCOUNTING = False;
  DEFAULT_PRIVILEGIES_CLEARING = False;
  DEFAULT_PRIVILEGIES_EDITING = False;
  DEFAULT_PRIVILEGIES_REPORTING = False;

implementation

end.
