<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
  <HEAD>
    <TITLE>Работа с базами данных справочно-информационного цеха МГТС РУП &laquo;Белтелеком&raquo;</TITLE>
    <META CONTENT="no-cache" HTTP-EQUIV="pragma">
    <META CONTENT="no-cache" HTTP-EQUIV="cache-control">
    <META CONTENT="Dynamic" NAME="Document-state">
    <META CONTENT="text/html; charset=Windows-1251" HTTP-EQUIV="Content-Type">
    <!--LINK REL="home" HREF="http://10.1.1.250/ns2/"-->
    <!--LINK REL="first" HREF="http://10.1.1.250/ns2/"-->
    <LINK REL="author" HREF="http://vladracoola.by.ru/index1.html">
    <STYLE MEDIA="screen, print" TYPE="text/css">
      * {
        font-family: Verdana, Arial, Helvetica, sans-serif;
        font-size: 8pt;
        padding: 0;
        margin: 0;
        border-color: transparent;
        border-width: 0;
        }
      TABLE, TD, TH {
        border-style: solid;
      }
      TABLE {
        table-layout: fixed;
        empty-cells: show;
        float: none;
        clear: both;
        border-collapse: collapse;
        background-color: white;
        }
    </STYLE>
  </HEAD>
  <BODY BGCOLOR="gainsboro">
    <FORM METHOD="POST" ACTION="" STYLE="margin: 15px 15px 0px 15px; padding-bottom: 15px;">
      <CENTER> <!-- Данный тэг необходим для выравнивания таблицы по центру в браузере MOZILLA --> 
      <TABLE BGCOLOR="WHITE" WIDTH="640" BORDER="0" ALIGN="CENTER" STYLE="border-color: black; border-width: 3;"> <!-- В данной строке выравнивание таблицы по центру - ALIGN="CENTER" корректно обрабатывается IE и OPERA - в MOZILLA не работает! -->
        <THEAD ALIGN="CENTER" VALIGN="MIDDLE">
          <TR>
            <TD WIDTH="13" ROWSPAN="3"></TD>
            <TD WIDTH="13" ROWSPAN="3"></TD>
            <TD HEIGHT="15" COLSPAN="2"></TD>
            <TD WIDTH="13" ROWSPAN="3"></TD>
            <TD WIDTH="13" ROWSPAN="3"></TD>
          </TR>
          <TR>
            <TD COLSPAN="2" STYLE="font-family: Times New Roman; font-weight: bold; font-size: 12pt;">Работа с базами данных справочно-информационного цеха МГТС<BR>РУП &laquo;Белтелеком&raquo;</TD>
          </TR>
          <TR>
            <TD HEIGHT="15" COLSPAN="3"></TD>
          </TR>
        </THEAD>
        <TFOOT ALIGN="CENTER" VALIGN="MIDDLE">
          <TR>
            <TD HEIGHT="15" COLSPAN="6"></TD>
          </TR>
          <TR>
            <TD COLSPAN="6">
              <INPUT TYPE="HIDDEN" NAME="step" VALUE="1">
              <INPUT TYPE="SUBMIT" VALUE="Далее >>>" STYLE="border-color: black; border-width: 2;" ONMOUSEOVER="window.status='Введите имя пользователя и пароль для доступа к АРМ и нажмите кнопку &laquo;Далее&raquo; для перехода к следующему шагу';" ONMOUSEOUT="window.status='';">
            </TD>
          </TR>
          <TR>
            <TD HEIGHT="15" COLSPAN="6"></TD>
          </TR>
        </TFOOT>
        <TBODY VALIGN="MIDDLE">
          <TR>
            <TD WIDTH="13" ROWSPAN="6"></TD>
            <TD WIDTH="13" ROWSPAN="6" BGCOLOR="#339999"></TD>
            <TD HEIGHT="15" COLSPAN="2" BGCOLOR="#339999"></TD>
            <TD WIDTH="13" ROWSPAN="6" BGCOLOR="#339999"></TD>
            <TD WIDTH="13" ROWSPAN="6"></TD>
          </TR>
          <TR>
            <TD COLSPAN="2" ALIGN="CENTER" BGCOLOR="#339999"><B>Введите данные пользователя:</B></TD>
          </TR>
          <TR>
            <TD HEIGHT="15" COLSPAN="2" BGCOLOR="#339999"></TD>
          </TR>
          <TR>
            <TD STYLE="padding: 3px 5px;">Имя пользователя</TD>
            <TD STYLE="padding: 3px 5px;"><INPUT STYLE="border: black solid 1px;" TYPE="TEXT" NAME="user" SIZE="30" VALUE=""></TD>
          </TR>
          <TR BGCOLOR="#EEEEEE">
            <TD STYLE="padding: 3px 5px;">Пароль</TD>
            <TD STYLE="padding: 3px 5px;"><INPUT STYLE="border: black solid 1px;" TYPE="PASSWORD" NAME="password" SIZE="30" VALUE=""></TD>
          </TR>
          <TR>
            <TD HEIGHT="15" COLSPAN="2" BGCOLOR="#339999"></TD>
          </TR>
        </TBODY>
  </BODY>
</HTML>