# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Название сервера')),
                ('Host', models.CharField(max_length=255, verbose_name='Наименование/адрес сервера')),
                ('Database', models.CharField(max_length=255, verbose_name='Наименование базы данных')),
                ('Priority', models.IntegerField(default=0, verbose_name='Приоритет обработки экспортов для домена (0 - самый высокий)')),
                ('Activity', models.BooleanField(default=False, verbose_name='Признак активности')),
                ('ChangeDate', models.DateTimeField(verbose_name='Дата последнего изменения записи')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
