unit DBUServerManager.uConsts;

interface

uses
  Winapi.Windows;

const
  APPLICATION_NAME = 'DBUServerManager';

  STATUSBAR_STATE_PANEL_NUMBER: Integer = 0;
  STATUSBAR_PROGRESS_PANEL_NUMBER: Integer = 1;
  STATUSBAR_SERVER_NAME: Integer = 2;
  STATUSBAR_HINT_PANEL_NUMBER: Integer = 3;

  INTERFACE_SECTION = 'Интерфейс';
  CONNECTION_SECTION = 'Подключение';
  OTHER_SECTION = 'Прочие';

  MESSAGE_TYPE_ERROR: Cardinal = MB_OK + MB_ICONERROR + MB_DEFBUTTON1;
  MESSAGE_TYPE_WARNING: Cardinal = MB_OK + MB_ICONWARNING + MB_DEFBUTTON1;
  MESSAGE_TYPE_CONFIRMATION_QUESTION: Cardinal = MB_OKCANCEL + MB_ICONQUESTION + MB_DEFBUTTON2;
  MESSAGE_TYPE_CONFIRMATION_WARNING_OK: Cardinal = MB_OKCANCEL + MB_ICONWARNING + MB_DEFBUTTON1;
  MESSAGE_TYPE_CONFIRMATION_WARNING_CANCEL: Cardinal = MB_OKCANCEL + MB_ICONWARNING + MB_DEFBUTTON2;

  CONFIGURATION_DEFAULT_ACTIVE_PAGE = 0;
  CONFIGURATION_DEFAULT_ENABLE_QUIT_CONFIRMATION = True;
  CONFIGURATION_DEFAULT_ENABLE_SPLASH_AT_START = True;
  CONFIGURATION_DEFAULT_ENABLE_STATUSBAR = True;
  CONFIGURATION_DEFAULT_ENABLE_TOOLBAR = True;
  CONFIGURATION_DEFAULT_ENABLE_STORE_MAINFORM_SIZES_AND_POSITION = True;
  CONFIGURATION_DEFAULT_ENABLE_ALWAYS_SHOW_TRAY_ICON = False;
  CONFIGURATION_DEFAULT_ENABLE_START_AT_TRAY = False;

  CONFIGURATION_DEFAULT_HOST = '';
  CONFIGURATION_DEFAULT_PORT = 6000;
  CONFIGURATION_DEFAULT_TIMEOUT = 30;
  CONFIGURATION_DEFAULT_ENABLE_STORE_LOGIN = False;
  CONFIGURATION_DEFAULT_ENABLE_STORE_PASSWORD = False;
  CONFIGURATION_DEFAULT_ENABLE_AUTO_LOGON = False;

  CONFIGURATION_DEFAULT_LOGIN = '';
  CONFIGURATION_DEFAULT_PASSWORD = '';

implementation

end.
