DROP TABLE IF EXISTS rne4._msr;
CREATE TABLE _msr (
  msr_id smallint(5) unsigned NOT NULL auto_increment,
  msr_erased enum('0','1') NOT NULL default '0',
  msr_start_datetime datetime default NULL,
  msr_stop_datetime datetime default NULL,
  msr_duration time default NULL,
  msr_organization_id smallint(5) unsigned default NULL,
  msr_is_premier enum('0','1') NOT NULL default '0',
  msr_is_tour enum('0','1') NOT NULL default '0',
  msr_for_children enum('0','1') NOT NULL default '0',
  msr_for_teenagers enum('0','1') NOT NULL default '0',
  msr_for_adults_only enum('0','1') NOT NULL default '0',
  msr_type text,
  msr_name text,
  msr_author text,
  msr_producer text,
  msr_performer text,
  msr_organizer text,
  msr_ticket_price text,
  msr_other_info mediumtext,
  msr_other_info_rtf mediumblob,
  msr_created_at datetime NOT NULL default '0000-00-00 00:00:00',
  msr_created_by_user_id tinyint(3) unsigned NOT NULL default '0',
  msr_modified_at datetime NOT NULL default '0000-00-00 00:00:00',
  msr_modified_by_user_id tinyint(3) unsigned NOT NULL default '0',
  PRIMARY KEY  (msr_id),
  UNIQUE KEY msr_id (msr_id),
  KEY msr_erased (msr_erased),
  KEY msr_organization_id (msr_organization_id),
  KEY msr_created_at (msr_created_at),
  KEY msr_created_by_user_id (msr_created_by_user_id),
  KEY msr_modified_at (msr_modified_at),
  KEY msr_modified_by_user_id (msr_modified_by_user_id),
  KEY msr_is_premier (msr_is_premier),
  KEY msr_is_tour (msr_is_tour),
  KEY msr_for_children (msr_for_children),
  KEY msr_for_teenagers (msr_for_teenagers),
  KEY msr_for_adults_only (msr_for_adults_only),
  KEY msr_start_datetime (msr_start_datetime),
  KEY msr_stop_datetime (msr_stop_datetime)
) TYPE=MyISAM COMMENT='Таблица мероприятий для версии 4.0';
INSERT INTO rne4._msr
SELECT
	NULL,
	"0",
	a.measurestartdatetime,
	a.measurestopdatetime,
	a.measureduration,
	a.organizationnameid,
	IF(a.measurepremier=1,"1","0"),
	"0",
	IF(a.childrenmeasure=1,"1","0"),
	IF(a.teenagersmeasure,"1","0"),
	"0",
	b.measuretype,
	c.measurename,
	d.measureauthor,
	e.measureproducer,
	a.measureperformer,
	a.measureorganizer,
	a.measureticketprice,
	a.measureinfo,
	NULL,
	"00000000000000",
	a.ridcreatorid,
	a.LMTS,
	a.ridcreatorid
FROM rne.measures a 
	LEFT JOIN rne.measuretypes b ON b.id=a.measuretypeid
	LEFT JOIN rne.measurenames c ON c.id=a.measurenameid
	LEFT JOIN rne.measureauthors d ON d.id=a.measureauthorid
	LEFT JOIN rne.measureproducers e ON e.id=a.measureproducerid
ORDER BY a.id;
