unit Beeper.uConsts;

interface

uses
  Winapi.Windows,
  Beeper.uTPeriodType,
  Beeper.uResourceStrings;

const
  MESSAGE_TYPE_ERROR: Cardinal = MB_OK + MB_ICONERROR + MB_DEFBUTTON1;
  MESSAGE_TYPE_CONFIRMATION: Cardinal = MB_OKCANCEL + MB_ICONQUESTION + MB_DEFBUTTON2;
  MESSAGE_TYPE_WARNING: Cardinal = MB_OK + MB_ICONWARNING + MB_DEFBUTTON1;

  DEFAULT_CONFIGURATION_SHOW_BALOON_HINTS = True;
  DEFAULT_CONFIGURATION_SOUND_ENABLED = True;
  DEFAULT_CONFIGURATION_MODIFIER_ON = MOD_SHIFT + MOD_ALT;
  DEFAULT_CONFIGURATION_VIRTUAL_KEY_ON = VK_F12;
  DEFAULT_CONFIGURATION_MODIFIER_OFF = MOD_CONTROL + MOD_ALT + MOD_SHIFT;
  DEFAULT_CONFIGURATION_VIRTUAL_KEY_OFF = VK_F12;

  DEFAULT_SIGNAL_COUNT = 0;
  DEFAULT_SIGNAL_TITLE = '';
  DEFAULT_SIGNAL_PERIOD = 0;
  DEFAULT_SIGNAL_PERIOD_TYPE = ptSeconds;
  DEFAULT_SIGNAL_MESSAGE_ENABLED = False;
  DEFAULT_SIGNAL_MESSAGE = '';
  DEFAULT_SIGNAL_WAVE_FILE_ENABLED = False;
  DEFAULT_SIGNAL_WAVE_FILE = '';
  DEFAULT_SIGNAL_ENABLED = True;

  PERIODS: array [low(TPeriodType) .. high(TPeriodType)] of string = (RsSeconds, RsMinutes, RsHours, RsDays, RsWeeks, RsMonths, RsYears);

  WAVEFILE_EXTENTION = 'wav';

  HOTKEY_ON = 1;
  HOTKEY_OFF = 2;

  APPLICATION_NAME = 'Beeper';

implementation

end.
